<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC0432J4-T440P" name="DisputeEndtoEndFlow_MessageTab.PayeeResponded_AdminInquiry" tests="1" failures="1" timestamp="6 Apr 2018 07:02:28 GMT" time="64.362" errors="0">
  <testcase name="DisputeApproval" time="64.362" classname="DisputeEndtoEndFlow_MessageTab.PayeeResponded_AdminInquiry">
    <failure type="java.lang.AssertionError" message="Failed TestCaseDisputeApproval">
      <![CDATA[java.lang.AssertionError: Failed TestCaseDisputeApproval
	at org.testng.Assert.fail(Assert.java:94)
	at com.calliduscloud.testing.util.SeleniumMethods.catch_code(SeleniumMethods.java:559)
	at DisputeEndtoEndFlow_MessageTab.PayeeResponded_AdminInquiry.DisputeApproval(PayeeResponded_AdminInquiry.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- DisputeApproval -->
</testsuite> <!-- DisputeEndtoEndFlow_MessageTab.PayeeResponded_AdminInquiry -->
